language: de

# Sorting mode for materials in the bag:
#   "alphabetical"  - by material name A→Z
#   "amount-desc"   - by stored amount, descending
sort-mode: "alphabetical"

auto-store-if-full: true
auto-store-message: true
show-open-hint: true
show-save-message: true