name: MaxInvPlugin
version: 2.4.1
main: de.maxinv.Main
api-version: "1.21"
commands:
  bag:
    description: Opens your bag. Subcommands: /bag [page], /bag search <query>, /bag clearsearch, /bag fav [add|remove] <MATERIAL>
    usage: /bag [page|search <query>|clearsearch|fav ...]